### ISSUE TITLE
关于配置静态资源

### ISSUE THREAD

**Issue by wjf2255** [Clouda-team/rapid-core#1]
rapid文档中没有介绍如何配置静态资源（css,js等），希望以后能更新。

**Comment by cnberg** [comment]
赞美第一个issue。

**Comment by wang-su** [comment]
文档后续会跟进. 简单的配法可以直接用通配符就成,  这么配就是把所有请求转到app目录下. 
{url:"/_", resource:"/app/_"}.  复杂的路径操作的,可以用正则 {url : /^\/(._?)\/what\/(._)/,resource : "/app/{1}/{2}"}

**Comment by huang-xin** [comment]
赞resource!
