### ISSUE TITLE
错误提示信息规避问题

### ISSUE THREAD

**Issue by wjf2255** [Clouda-team/rapid-core#3]
程序出错后，会把错误信息打印到页面上（sendError），暴露程序程序存放的物理位置。这个问题应该如何避免？

**Comment by wang-su** [comment]
使用rapid-httpserver的sendError方法最终都会forword到erroraction上, 直接使用自定义的errorAction,自行处理异常.
0.1版本以前直接定义名称为error的action.
0.1版本之后不使用固定名称,可以随意定义任意名称的action然后, 在配置文件中指明errorAction所使用的action名称.

**Comment by cnberg** [comment]
最好做一个开关可配置关闭吧，上线后不输出到页面上，线下可以打开这个开关用来调试

## 

Sincerely
Berg Lei
