### ISSUE TITLE
小哥，这是咋回事：RapidJS快速入门，启动不了

### ISSUE THREAD

**Issue by aristoler** [Clouda-team/rapid-core#4]
node start
Welecome!! Initialize RapidJS!!
Timeout : waiting the config of rapid-log , will be auth-start by default config
[INFO][2015-01-14T08:10:12.494Z] rapid-log start...; (at watchConfig (E:\DevWorkspace\Clouda\RapidJs\node_modules\rapid-core\src\log.js:199:13))
[DEV][2015-01-14T08:10:12.498Z]

====== ENV PARAMS ======

ROOT_DIR : E:\DevWorkspace\Clouda\RapidJs\
USER_DIR : E:\DevWorkspace\Clouda\RapidJs\app\
CONF_DIR : E:\DevWorkspace\Clouda\RapidJs\conf\

====== END ENV PARAMS =======
; (at stdLog (E:\DevWorkspace\Clouda\RapidJs\node_modules\rapid-core\src\rapid-core.js:19:13))
[INFO][2015-01-14T08:10:12.499Z] Plug-in : Loaded [rapid-log]; (at stdLog (E:\DevWorkspace\Clouda\RapidJs\node_modules\rapid-core\src\rapid-core.js:19:13))
[INFO][2015-01-14T08:10:12.502Z] Initialize rapid Http Server...; (at Object.<anonymous> (E:\DevWorkspace\Clouda\RapidJs\node_modules\rapid-httpserver\httpd.js:341:6))
[INFO][2015-01-14T08:10:12.503Z] Plug-in : Loaded [rapid-httpserver]; (at stdLog (E:\DevWorkspace\Clouda\RapidJs\node_modules\rapid-core\src\rapid-core.js:19:13))

**Comment by wang-su** [comment]
看下配置文件. 貌似是httpserver的配置不存在,或者存在但是没配成auth start,而且也没手动执行start.

**Comment by superlbr** [comment]
@aristoler 估计你文件路径不对，仔细看看撒

**Comment by xiashulin** [comment]
我也遇到这个问题，楼主是如何解决的

**Comment by xiashulin** [comment]
大意失荆州啊

**Comment by CancerJun** [comment]
@aristoler 
conf 目录是放在welcome 下面，不是放在app下面
